const news=[
 {title:"NCEC continues contractor qualification program",date:"2026-08-09"},
 {title:"Baghdad housing project preparation resumed",date:"2026-08-08"},
 {title:"Steel price remains stable",date:"2026-08-07"},
 {title:"New infrastructure package announced",date:"2026-08-07"},
 {title:"Electricity sector investment discussion",date:"2026-08-06"}
];

const centerTextPlugin={id:"ivipCenterText",afterDraw(chart){const area=chart.chartArea;if(!area)return;const ctx=chart.ctx;const total=chart.data.datasets?.[0]?.data?.reduce((a,b)=>a+Number(b||0),0)||0;const approved=Number(chart.data.datasets?.[0]?.data?.[0]||0);const pct=total?Math.round(approved/total*100):0;const x=(area.left+area.right)/2,y=(area.top+area.bottom)/2;ctx.save();ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillStyle="#0f172a";ctx.font="700 18px Inter, Arial";ctx.fillText(pct+"%",x,y);ctx.restore();}};

function renderNews(){const list=document.getElementById("newsList");if(!list)return;list.innerHTML="";news.forEach(n=>{const li=document.createElement("li");li.innerHTML=`<span>${n.title}</span><span class="news-date"><i data-lucide="calendar-days"></i>${n.date}</span>`;list.appendChild(li)});if(window.lucide)lucide.createIcons();}
function updateRecentCompanies(){if(typeof vendors==="undefined")return;const box=document.getElementById("recentCompanies");if(!box)return;box.innerHTML="";vendors.slice().reverse().slice(0,3).forEach(v=>{const card=document.createElement("div");card.className="recent-card";card.innerHTML=`<div class="recent-icon"><i data-lucide="building-2"></i></div><div class="recent-main"><h4>${v.name||""}</h4><p>${v.category||""}</p></div><div class="recent-meta"><div>${v.location||v.city||""}</div><div>${v.lastUpdate||""}</div></div>`;box.appendChild(card)});if(window.lucide)lucide.createIcons();}
let surveyChart=null;
function updateSurveySummary(approved,pending,total){const pct=total?Math.round(approved/total*100):0;const a=document.getElementById("surveyApprovalPercent"),b=document.getElementById("surveyApproved"),p=document.getElementById("surveyPending"),t=document.getElementById("surveyTotal");if(a)a.textContent=pct+"%";if(b)b.textContent=approved;if(p)p.textContent=pending;if(t)t.textContent=total;}
function updateSurveyChart(){if(typeof vendors==="undefined")return;const canvas=document.getElementById("surveyChart");if(!canvas||typeof Chart==="undefined")return;const approved=vendors.filter(v=>v.approval==="Approved").length;const pending=vendors.filter(v=>v.approval!=="Approved").length;const total=vendors.length;updateSurveySummary(approved,pending,total);if(!surveyChart){surveyChart=new Chart(canvas.getContext("2d"),{type:"doughnut",data:{labels:["Approved","Pending"],datasets:[{data:[approved,pending],backgroundColor:["#2F9FE3","#F59E0B"],borderWidth:0}]},plugins:[centerTextPlugin],options:{responsive:true,maintainAspectRatio:false,cutout:"68%",rotation:-90,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>` ${c.label}: ${c.raw}`}}}}});}else{surveyChart.data.datasets[0].data=[approved,pending];surveyChart.update();}}
function initDashboard(){renderNews();updateRecentCompanies();updateSurveyChart();const allC=document.getElementById("viewAllCompanies");if(allC)allC.addEventListener("click",()=>{document.querySelector(".vendor-workspace")?.scrollIntoView({behavior:"smooth",block:"start"});});const allN=document.getElementById("viewAllNews");if(allN)allN.addEventListener("click",()=>{document.querySelector(".news-panel")?.scrollIntoView({behavior:"smooth",block:"center"});});}
document.addEventListener("DOMContentLoaded",initDashboard);
console.log("IVIP Dashboard Script Loaded");
